#!/usr/bin/env bash
# Run ON THE PI as root before shutting it down for imaging.
# Strips logs, caches, secrets, and host-specific IDs so the golden
# image starts completely fresh on every new flash.
#
# Usage (on the Pi):
#   sudo bash /home/pi/BigA/scripts/prep_golden.sh

set -euo pipefail

if [ "$(id -u)" -ne 0 ]; then
  echo "Run as root: sudo bash $0"
  exit 1
fi

echo "========================================"
echo "  BigA — Golden Image Prep"
echo "========================================"

# Stop BigA services so nothing is writing during cleanup
echo ""
echo "[1/9] Stopping BigA services..."
systemctl stop biga biga-portal biga-reset biga-update 2>/dev/null || true

# Package caches
echo "[2/9] Cleaning package caches..."
apt-get clean -qq
apt-get autoremove -y -qq

# Logs
echo "[3/9] Clearing logs..."
journalctl --vacuum-time=1d 2>/dev/null || true
rm -f /var/log/biga*.log /var/log/biga_update.log
truncate -s 0 /tmp/biga.log 2>/dev/null || true
find /var/log -type f \( -name "*.log" -o -name "*.gz" \) -delete 2>/dev/null || true

# Temp files
echo "[4/9] Clearing temp files..."
rm -rf /tmp/* /var/tmp/* 2>/dev/null || true

# Remove stale SSH deploy keys from golden images (public repo uses HTTPS OTA).
# Manual build Pis can re-run scripts/setup_deploy_key.sh and set BIGA_GIT_USE_DEPLOY_KEY=1.
rm -f /etc/biga/deploy_key /etc/biga/deploy_key.pub 2>/dev/null || true

# WiFi credentials — user provisions via portal on first boot
echo "[5/9] Removing saved WiFi credentials..."
rm -f /etc/biga/wifi_creds.json
rm -f /etc/biga/provisioning_active
rm -f /home/pi/BigA/.biga_game_state.json /home/pi/BigA/.biga_game_state.tmp
# NOTE: /etc/biga/deploy_key is intentionally preserved — it is the
# read-only SSH deploy key that lets the Pi pull from the private repo.

# Downloaded MLB highlights — large; each golden flash should fetch its own.
echo "[6/9] Removing downloaded game highlights..."
HIGHLIGHTS_DIR="/home/pi/BigA/src/pi_tracker/assets/highlights"
if [ -d "$HIGHLIGHTS_DIR" ]; then
    rm -rf "${HIGHLIGHTS_DIR:?}"/*
    echo "  → wiped ${HIGHLIGHTS_DIR}/*"
fi
mkdir -p "$HIGHLIGHTS_DIR"
chown pi:pi "$HIGHLIGHTS_DIR" 2>/dev/null || true

# Remove all NetworkManager WiFi client connections so the golden image
# doesn't carry the build Pi's home network. The biga-ap profile is kept.
echo "  → wiping NM WiFi client connections..."
nmcli -t -f NAME,TYPE connection show \
    | grep ':802-11-wireless$' \
    | cut -d: -f1 \
    | grep -v '^biga-ap$' \
    | while IFS= read -r con; do
        nmcli connection delete "$con" 2>/dev/null && echo "  → deleted: $con" || true
      done

# Reset the firstboot sentinel so the AP profile is regenerated on the new Pi's MAC.
rm -f /etc/biga/.firstboot_done

# SSH host keys — auto-regenerated by Pi OS on first boot
echo "[7/9] Removing SSH host keys (will regenerate on first boot)..."
rm -f /etc/ssh/ssh_host_*

# machine-id — must be unique per host; blank triggers regeneration on boot
echo "[8/9] Resetting machine-id..."
truncate -s 0 /etc/machine-id
rm -f /var/lib/dbus/machine-id  # symlink on modern systemd; harmless if missing

# fake-hwclock — Pi Zero has no RTC; seed near now so pre-NTP date.today() is sane
echo "  → seeding fake-hwclock for first boot…"
TZ=America/Los_Angeles date -Iseconds > /etc/fake-hwclock.data

# Shell histories
echo "[9/9] Clearing shell histories..."
truncate -s 0 /root/.bash_history 2>/dev/null || true
truncate -s 0 /home/pi/.bash_history 2>/dev/null || true
history -c 2>/dev/null || true

echo ""
echo "========================================"
echo "  Prep complete."
echo "  Shutting down in 5 seconds..."
echo "  Remove the SD card after the green"
echo "  activity LED stops blinking."
echo "========================================"
sleep 5
shutdown -h now
