#!/usr/bin/env bash
# Run ON THE PI as root before shutting it down for imaging.
# Strips logs, caches, secrets, and host-specific IDs so the golden
# image starts completely fresh on every new flash.
#
# Usage (on the Pi):
#   sudo bash /home/pi/BigA/scripts/prep_golden.sh

set -euo pipefail

if [ "$(id -u)" -ne 0 ]; then
  echo "Run as root: sudo bash $0"
  exit 1
fi

echo "========================================"
echo "  BigA — Golden Image Prep"
echo "========================================"

# Stop BigA services so nothing is writing during cleanup
echo ""
echo "[1/8] Stopping BigA services..."
systemctl stop biga biga-portal biga-reset biga-update 2>/dev/null || true

# Package caches
echo "[2/8] Cleaning package caches..."
apt-get clean -qq
apt-get autoremove -y -qq

# Logs
echo "[3/8] Clearing logs..."
journalctl --vacuum-time=1d 2>/dev/null || true
rm -f /var/log/biga*.log /var/log/biga_update.log
truncate -s 0 /tmp/biga.log 2>/dev/null || true
find /var/log -type f \( -name "*.log" -o -name "*.gz" \) -delete 2>/dev/null || true

# Temp files
echo "[4/8] Clearing temp files..."
rm -rf /tmp/* /var/tmp/* 2>/dev/null || true

# WiFi credentials — user provisions via portal on first boot
echo "[5/8] Removing saved WiFi credentials..."
rm -f /etc/biga/wifi_creds.json
# NOTE: /etc/biga/deploy_key is intentionally preserved — it is the
# read-only SSH deploy key that lets the Pi pull from the private repo.

# Remove all NetworkManager WiFi client connections so the golden image
# doesn't carry the build Pi's home network. The biga-ap profile is kept.
echo "  → wiping NM WiFi client connections..."
nmcli -t -f NAME,TYPE connection show \
    | grep ':802-11-wireless$' \
    | cut -d: -f1 \
    | grep -v '^biga-ap$' \
    | while IFS= read -r con; do
        nmcli connection delete "$con" 2>/dev/null && echo "  → deleted: $con" || true
      done

# Reset the firstboot sentinel so the AP profile is regenerated on the new Pi's MAC.
rm -f /etc/biga/.firstboot_done

# SSH host keys — auto-regenerated by Pi OS on first boot
echo "[6/8] Removing SSH host keys (will regenerate on first boot)..."
rm -f /etc/ssh/ssh_host_*

# machine-id — must be unique per host; blank triggers regeneration on boot
echo "[7/8] Resetting machine-id..."
truncate -s 0 /etc/machine-id
rm -f /var/lib/dbus/machine-id  # symlink on modern systemd; harmless if missing

# Shell histories
echo "[8/8] Clearing shell histories..."
truncate -s 0 /root/.bash_history 2>/dev/null || true
truncate -s 0 /home/pi/.bash_history 2>/dev/null || true
history -c 2>/dev/null || true

echo ""
echo "========================================"
echo "  Prep complete."
echo "  Shutting down in 5 seconds..."
echo "  Remove the SD card after the green"
echo "  activity LED stops blinking."
echo "========================================"
sleep 5
shutdown -h now
